### ISSUE TITLE
Ballistic-PBX Run Error

### ISSUE THREAD

**Issue by Bigben83** [jonathan-roper/Ballistic-PBX#6]
when trying to run this script with the command
`sudo /bin/sh install-ballistic-pbx.sh`
it throws an error of
36: install-ballistic-pbx.h: Syntax error: "(" unexpected

what is causing this and how do you fix it. ?

**Comment by jonathan-roper** [comment]
This works for me. Make sure you copy the raw version from https://raw.githubusercontent.com/jonathan-roper/Ballistic-PBX/master/install-ballistic-pbx.sh, then logged as root, execute "bash install-ballistic.sh" (change the filename to suite)
